spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hethong.chocostyle@gmail.com
spring.mail.password=rjwh ourf yhki ntaw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.max-http-request-header-size=10MB
# --- C?U HÌNH FACEBOOK ---
spring.security.oauth2.client.registration.facebook.client-id=2330656364095688
spring.security.oauth2.client.registration.facebook.client-secret=1d42b78b360f598634606a7784f7b8a0
spring.security.oauth2.client.registration.facebook.scope=email, public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook


# --- C?U HÌNH ??NG NH?P GOOGLE ---
spring.security.oauth2.client.registration.google.client-id=638026137500-vhv73b6lgc3mn24neu8g46vsjhtj1i7v.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email, profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

gemini.api.keys=AIzaSyAIT018_uyOcOR_NbDt9W0GFiwtgS3_k8w,AIzaSyCjy2DrVaWUUkRMEcQOiHn2LQ0S_XWoLbI,AIzaSyCVyMypS5h9koMpHcBVmV-p_Jg364RLvkU,AIzaSyCaAY7YY1PmxPJjdyRAQFNnJo4c00-zDLk